server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: FeeService
          uri: lb://FeeService
          predicates:
            - Path=/fee/**
        - id: TransferService
          uri: lb://TransferService
          predicates:
            - Path=transfer/**
        - id: Exception
          uri: lb://ExceptionService
          predicates:
            - Path=/exception/**
